### ISSUE TITLE
ip175l P0 - P3 口和cpu port 不能通信

### ISSUE THREAD

**Issue by tomyqg** [blueprt/lwipport#1]
请教下IP175L要通过单片机的MAC收发到交换机其他口上的数据需要啥特殊配置不，还是默认P0 -- P3口的数据就会转发到P5上（P5已配置为 RMII PHY模式）？

**Comment by blueprt** [comment]
本质就是一个交换机，ip175自身的mac地址学习，除非额外设置，会根据mac匹配相应端口转发，部分特殊mac地址(ieee保留的部分）设置后也会转发给cpu

**Comment by blueprt** [comment]
> 

这个驱动不是完整的，只实现基本功能和qos相关功能，具体的还是需要看官方文档

**Comment by tomyqg** [comment]
[IP175B_IP175L_IP175D.zip](https://github.com/blueprt/lwipport/files/11877421/IP175B_IP175L_IP175D.zip)
`struct _Mirror_setting Mirror_setting;
		
		memset(&Mirror_setting,0,sizeof(Mirror_setting));
		//fill value///////////////////////////
		Mirror_setting.enable=1;	//0:disable !0:enable
		Mirror_setting.mode = MIRROR_MODE_TXnRX;
		//MODE_TX:just mirror tx port
		//MODE_RX:just mirror rx port
		//MODE_TX2RX: mirror tx+rx port, and TX/RX port must be different
		//MODE_TXnRX: mirror tx+rx port, and TX/RX port must be the same
		Mirror_setting.tx_from=0;
		Mirror_setting.rx_from=0;
		Mirror_setting.to=5;		//capture p0's TX and p2's Rx to p5(CPU)
		Mirror_Set(&psNuEmac->ip175, &Mirror_setting);`

我用官方linux驱动的这个接口，设置端口镜像都没有任何反应（寄存器配置成功了，新做的硬件，也不知道有无问题），大佬有做好的板子可以出售不？
